pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker {
          image 'maven:3.8.1-adoptopenjdk-11'
        }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Build') {
      steps {
        script {
          // Clean up previous build artifacts if necessary
          deleteDir()

          // Compile and build the Java program
          sh 'javac HelloWorld.java'
          // Run the Java program
          sh 'java HelloWorld'
        }
      }
      /*stage('Front-end') {
        agent {
          docker { image 'node:16-alpine' }
        }
        steps {
          sh 'node --version'
        }
      }*/
    }
  }
}
