pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                    // Clean up previous build artifacts if necessary
                    deleteDir()

                    // Compile and build the Java program
                    sh 'javac HelloWorld.java'
                }
            }
        }
        stage('Run') {
            steps {
                script {
                    // Run the Java program
                    sh 'java HelloWorld'
                }
            }
        }
    }
}
