pipeline {
    agent none
    
    stages {
        stage('Back-end') {
        agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
        }
          steps {
            sh 'mvn --version'
          }
        }
        stage('Build') {
            steps {
                script {
                    // Clean up previous build artifacts if necessary
                    deleteDir()

                    // Compile and build the Java program
                    sh 'javac HelloWorld.java'
                }
            }
        }
        stage('Run') {
            steps {
                script {
                    // Run the Java program
                    sh 'java HelloWorld'
                }
            }
        }
    }
}
